CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_BT_DEVICE_NAME="poached-eggs"

# --- Prospector Scanner (Status Advertisement) ---
CONFIG_ZMK_STATUS_ADVERTISEMENT=y
CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="poached-eggs"
CONFIG_ZMK_STATUS_ADV_CENTRAL_SIDE="LEFT"

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Right 1台を接続する
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

# Right が接続するまで広告を接続待ちモードにする
CONFIG_PROSPECTOR_EXPECTED_PERIPHERAL_COUNT=1

# Prospector の右側バッテリー表示
CONFIG_ZMK_STATUS_ADV_HALF_PERIPHERAL=0
